name: cazuapp
description: Delivery at convenience.  


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.0-146.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bcrypt: ^1.1.3

  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  formz: ^0.6.0
  dio: ^5.1.2
  flutter_dotenv: ^5.1.0
  battery_info: ^1.1.1
  shared_preferences: ^2.2.1
  stream_transform: ^2.1.0
  bloc_concurrency: ^0.2.2
  url_launcher: ^6.1.11
  geolocator: ^10.0.0
  connectivity_plus: ^5.0.1
  json_annotation: ^4.8.0
  font_awesome_flutter: ^10.4.0
  intl: ^0.19.0
  keyboard_detection: ^0.7.0
  flutter_native_splash: ^2.2.18
  badges: ^3.1.1
  cli_util: ^0.4.0
  jiffy: ^6.2.1
  dropdown_button2: ^2.1.4
  flutter_launcher_icons: ^0.13.1
  loading_animation_widget: ^1.2.0+4
  flutter_screenutil: ^5.9.0

flutter_icons:
  image_path_android: 'assets/launch/icon.png'
  image_path_ios: 'assets/launch/icon.png'
  android: true
  ios: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/launch/
    - assets/images/
