name: main-app

on:
  push:
    branches:
      - unstable
  pull_request:
    branches:
      - unstable

jobs:
  build-and-format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Dart
      uses: dart-lang/setup-dart@v1
      with:
        dart-version: 'stable' # Use 'stable' for the latest stable version, or specify a version like '2.14.0'

    - name: Install dependencies
      run: dart pub get

    - name: Verify formatting
      run: dart format --set-exit-if-changed .

    - name: Run tests # Optional step if you have tests
      run: dart test